services:
  redis:
    image: redis:latest
    container_name: redis-standalone
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass vivelenosql
    volumes:
      - redis-data:/data
    networks:
      - redis-net

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "8001:8001"
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
    driver: bridge
