services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Penholder9-Commodore4-Nutshell0-Empower9-Removed7-Sternum6
    volumes:
      - /volume3/docker/nosql:/data/db
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Penholder9-Commodore4-Nutshell0-Empower9-Removed7-Sternum6
      ME_CONFIG_MONGODB_URL: "mongodb://root:Penholder9-Commodore4-Nutshell0-Empower9-Removed7-Sternum6@mongo:27017/"
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: Impale4-Deranged2-Backside8-Euphemism0-Derived6-Unboxed4
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge